// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKPOHfRUyVHfShpvCg8-bzDnoTqQb0nS8',
    appId: '1:1044490470218:web:0245013e4c55f4f9ae37b3',
    messagingSenderId: '1044490470218',
    projectId: 'crud-fproject',
    authDomain: 'crud-fproject.firebaseapp.com',
    storageBucket: 'crud-fproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRbZvbtWlL--IpCysVFpR9U70asVXzeKM',
    appId: '1:1044490470218:android:2823caed567fb585ae37b3',
    messagingSenderId: '1044490470218',
    projectId: 'crud-fproject',
    storageBucket: 'crud-fproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJOjUySEKwm426mYdJz76wUdGJzB20EKk',
    appId: '1:1044490470218:ios:d661a1c97c9666d4ae37b3',
    messagingSenderId: '1044490470218',
    projectId: 'crud-fproject',
    storageBucket: 'crud-fproject.appspot.com',
    iosBundleId: 'com.example.crudFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJOjUySEKwm426mYdJz76wUdGJzB20EKk',
    appId: '1:1044490470218:ios:d661a1c97c9666d4ae37b3',
    messagingSenderId: '1044490470218',
    projectId: 'crud-fproject',
    storageBucket: 'crud-fproject.appspot.com',
    iosBundleId: 'com.example.crudFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKPOHfRUyVHfShpvCg8-bzDnoTqQb0nS8',
    appId: '1:1044490470218:web:4216f2c8239d7782ae37b3',
    messagingSenderId: '1044490470218',
    projectId: 'crud-fproject',
    authDomain: 'crud-fproject.firebaseapp.com',
    storageBucket: 'crud-fproject.appspot.com',
  );

}